openapi: 3.0.3
info:
  title: Deep3 Labs API
  description: ''
  version: v0.0.3
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      name: x-api-key
      in: header
  schemas:
    ChainsResponse:
      type: object
      properties:
        chainId:
          type: number
        name:
          type: string
        models:
          type: array
          items:
            type: string
      required:
        - chainId
        - name
        - models
    ModelsResponse:
      type: object
      properties:
        name:
          type: string
        chains:
          type: array
          items:
            type: number
      required:
        - name
        - chains
    model:
      type: string
    chainId:
      type: number
    publicAddress:
      type: string
      pattern: ^0x[a-fA-F0-9]{40}$
    PredictionResponse:
      type: object
      properties:
        code:
          type: number
        result:
          type: number
      required:
        - code
    HodlerResponse:
      type: object
      properties:
        code:
          type: number
        result:
          type: number
      required:
        - code
    address:
      type: string
      pattern: ^0x[a-fA-F0-9]{40}$
    HodlC1Response:
      type: object
      properties:
        code:
          type: number
        result:
          type: number
      required:
        - code
    HodlC1XTokenRequest:
      type: object
      properties:
        address:
          type: string
        mappings:
          type: array
          items:
            type: object
            properties:
              chainId:
                type: number
              address:
                type: string
            required:
              - chainId
              - address
      required:
        - address
    HodlC1XTokenResponse:
      type: object
      properties:
        code:
          type: number
        result:
          type: number
      required:
        - code
    HodlC1XTokensRequest:
      type: object
      properties:
        addresses:
          type: array
          items:
            type: object
            properties:
              address:
                type: string
              mappings:
                type: array
                items:
                  type: object
                  properties:
                    chainId:
                      type: number
                    address:
                      type: string
                  required:
                    - chainId
                    - address
            required:
              - address
    HodlC1XTokensResponse:
      type: array
      items:
        type: object
        properties:
          address:
            type: string
          result:
            type: number
        required:
          - address
    StakeSageLResponse:
      type: object
      properties:
        code:
          type: number
        result:
          type: number
      required:
        - code
    StakeSageHResponse:
      type: object
      properties:
        code:
          type: number
        result:
          type: number
      required:
        - code
security:
  - ApiKey: []
paths:
  /chains:
    get:
      summary: Get currently supported chains and the active machine learning models
      description: Will return currently supported chains
      operationId: getChains
      parameters: []
      tags:
        - Deep3
      responses:
        '200':
          description: A list of chain objects
          content:
            application/json:
              examples:
                success:
                  summary: A successful response
                  description: >-
                    An array of currently supported chains and the machine
                    learning models that support them will be returned
                  value:
                    - chainId: 1
                      name: Ethereum Mainnet
                      models:
                        - HODL-C1
              schema:
                $ref: '#/components/schemas/ChainsResponse'
  /models:
    get:
      summary: Get active machine learning models and the chains they support
      description: Will return active machine learning models
      operationId: getModels
      parameters: []
      tags:
        - Deep3
      responses:
        '200':
          description: A list of model objects
          content:
            application/json:
              examples:
                success:
                  summary: A successful response
                  description: >-
                    An array of active machine learning models and the chains
                    they support will be returned
                  value:
                    - model: HODL-C1
                      chains:
                        - 1
              schema:
                $ref: '#/components/schemas/ModelsResponse'
  /prediction/{model}/{chainId}/{publicAddress}:
    get:
      summary: Get a prediction
      description: Will return the prediction
      operationId: getPrediction
      parameters:
        - name: model
          in: path
          description: The model for the prediction
          required: true
          schema:
            $ref: '#/components/schemas/model'
        - name: chainId
          in: path
          description: The chain id for the prediction
          required: true
          schema:
            $ref: '#/components/schemas/chainId'
        - name: publicAddress
          in: path
          description: The public address to predict
          required: true
          schema:
            $ref: '#/components/schemas/publicAddress'
      tags:
        - Deep3
      responses:
        '200':
          description: A prediction object
          content:
            application/json:
              examples:
                available:
                  summary: A prediction is available
                  description: >-
                    When a prediction is available for the address it will
                    return a 200 code and the result
                  value:
                    code: 200
                    result: 0.32
                unavailable:
                  summary: A prediction is not available
                  description: >-
                    If there is not a prediction for the address it will return
                    a 204 code and a null result
                  value:
                    code: 204
                    result: null
              schema:
                $ref: '#/components/schemas/PredictionResponse'
  /hodler/{chainId}/{publicAddress}:
    get:
      summary: Get a Hodler prediction
      description: Will return the prediction
      operationId: getHodlerPrediction
      parameters:
        - name: chainId
          in: path
          description: The chain id for the prediction
          required: true
          schema:
            $ref: '#/components/schemas/chainId'
        - name: publicAddress
          in: path
          description: The public address for the wallet
          required: true
          schema:
            $ref: '#/components/schemas/publicAddress'
      tags:
        - Deep3
      deprecated: true
      responses:
        '200':
          description: A prediction object
          content:
            application/json:
              examples:
                available:
                  summary: A prediction is available
                  description: >-
                    When a prediction is available for the address it will
                    return a 200 code and the result
                  value:
                    code: 200
                    result: 0.32
                unavailable:
                  summary: A prediction is not available
                  description: >-
                    If there is not a prediction for the address it will return
                    a 204 code and a null result
                  value:
                    code: 204
                    result: null
              schema:
                $ref: '#/components/schemas/HodlerResponse'
  /hodl-c1/chain/{chainId}/account/{address}:
    get:
      summary: Get a HODL-C1 prediction
      description: Will return the prediction
      operationId: getHodlC1Prediction
      parameters:
        - name: chainId
          in: path
          description: The chain id for the prediction
          required: true
          schema:
            $ref: '#/components/schemas/chainId'
        - name: address
          in: path
          description: The address for the account
          required: true
          schema:
            $ref: '#/components/schemas/address'
      tags:
        - Deep3
      responses:
        '200':
          description: A prediction object
          content:
            application/json:
              examples:
                available:
                  summary: A prediction is available
                  description: >-
                    When a prediction is available for the address it will
                    return a 200 code and the result
                  value:
                    code: 200
                    result: 0.32
                unavailable:
                  summary: A prediction is not available
                  description: >-
                    If there is not a prediction for the address it will return
                    a 204 code and a null result
                  value:
                    code: 204
                    result: null
              schema:
                $ref: '#/components/schemas/HodlC1Response'
  /hodl-c1/x/token:
    post:
      summary: Get a HODL-C1 cross-chain token prediction
      description: Will return the prediction
      operationId: getHodlC1XTokenPrediction
      parameters: []
      tags:
        - Deep3
      requestBody:
        description: >-
          An object with a primary token address and any mappings for different
          chain addresses
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HodlC1XTokenRequest'
      responses:
        '200':
          description: A prediction object
          content:
            application/json:
              examples:
                available:
                  summary: A prediction is available
                  description: >-
                    When a prediction is available for the address it will
                    return a 200 code and the result
                  value:
                    code: 200
                    result: 32
                unavailable:
                  summary: A prediction is not available
                  description: >-
                    If there is not a prediction for the address it will return
                    a 204 code and a null result
                  value:
                    code: 204
                    result: null
              schema:
                $ref: '#/components/schemas/HodlC1XTokenResponse'
  /hodl-c1/x/tokens:
    post:
      summary: Get HODL-C1 cross-chain token predictions
      description: Will return the predictions
      operationId: getHodlC1XTokenPredictions
      parameters: []
      tags:
        - Deep3
      requestBody:
        description: >-
          An array of objects with a primary token address and any mappings for
          different chain addresses
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HodlC1XTokensRequest'
      responses:
        '200':
          description: A prediction object
          content:
            application/json:
              examples:
                available:
                  summary: A prediction is available
                  description: >-
                    When a prediction is available for an address it will return
                    a result
                  value:
                    - address: '0x0000000000000000000000000000000000000000'
                      result: 32
                unavailable:
                  summary: A prediction is not available
                  description: >-
                    If there is not a prediction for an address it will return a
                    null result
                  value:
                    - address: '0x0000000000000000000000000000000000000000'
                      result: null
              schema:
                $ref: '#/components/schemas/HodlC1XTokensResponse'
  /stakesage-l/chain/{chainId}/account/{address}:
    get:
      summary: Get a StakeSage-L prediction
      description: Will return the prediction
      operationId: getStakeSageLPrediction
      parameters:
        - name: chainId
          in: path
          description: The chain id for the prediction
          required: true
          schema:
            $ref: '#/components/schemas/chainId'
        - name: address
          in: path
          description: The address for the account
          required: true
          schema:
            $ref: '#/components/schemas/address'
      tags:
        - Deep3
      responses:
        '200':
          description: A prediction object
          content:
            application/json:
              examples:
                available:
                  summary: A prediction is available
                  description: >-
                    When a prediction is available for the address it will
                    return a 200 code and the result
                  value:
                    code: 200
                    result: 0.32
                unavailable:
                  summary: A prediction is not available
                  description: >-
                    If there is not a prediction for the address it will return
                    a 204 code and a null result
                  value:
                    code: 204
                    result: null
              schema:
                $ref: '#/components/schemas/StakeSageLResponse'
  /stakesage-h/chain/{chainId}/account/{address}:
    get:
      summary: Get a StakeSage-H prediction
      description: Will return the prediction
      operationId: getStakeSageHPrediction
      parameters:
        - name: chainId
          in: path
          description: The chain id for the prediction
          required: true
          schema:
            $ref: '#/components/schemas/chainId'
        - name: address
          in: path
          description: The address for the account
          required: true
          schema:
            $ref: '#/components/schemas/address'
      tags:
        - Deep3
      responses:
        '200':
          description: A prediction object
          content:
            application/json:
              examples:
                available:
                  summary: A prediction is available
                  description: >-
                    When a prediction is available for the address it will
                    return a 200 code and the result
                  value:
                    code: 200
                    result: 0.32
                unavailable:
                  summary: A prediction is not available
                  description: >-
                    If there is not a prediction for the address it will return
                    a 204 code and a null result
                  value:
                    code: 204
                    result: null
              schema:
                $ref: '#/components/schemas/StakeSageHResponse'
servers:
  - url: https://api.deep3.ai/v0/
    description: live
tags:
  - name: Deep3
    description: The Deep3 Labs API
